svh/urls.py
from unicodedata import name
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from .views import (
    ResultsListView,
    ReportListView,
    ReportDetailView,
    PlayerListView,
    PlayingScheduleListView,
    StatsListView,
    ContactView,
    ContactSuccessView,
)

from . import views

app_name = "svh"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "results/",
        ResultsListView.as_view(template_name="svh/matchresult_list.html"),
        name="results",
    ),
    path("reports/", ReportListView.as_view(), name="reports"),
    path("reports/<pk>/", ReportDetailView.as_view(), name="report-detail"),
    path("players/", PlayerListView.as_view(), name="players"),
    path("schedule/", PlayingScheduleListView.as_view(), name="schedule"),
    path("stats/", StatsListView.as_view(template_name="svh/stats.html"), name="stats"),
    path("about/", TemplateView.as_view(template_name="svh/about.html")),
    path("contact/", ContactView.as_view(), name="contact"),
    path("success/", ContactSuccessView.as_view(), name="success"),
    path("tinymce/", include("tinymce.urls")),
    path("impressum/", TemplateView.as_view(template_name="svh/impressum.html")),
    path("datenschutz/", TemplateView.as_view(template_name="svh/datenschutz.html")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svhoerne/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("svh.urls")),
    path("admin/", admin.site.urls),
]

svh/models.py
from operator import mod
from pyexpat import model
from typing import Any
from django.db import models
from tinymce.models import HTMLField

# Create your models here.
class Team(models.Model):
    teamId = models.BigAutoField(primary_key=True)
    long_name = models.CharField(
        "Name", max_length=200, help_text="Vollständiger Name der Mannschaft"
    )
    short_name = models.CharField(
        "Kürzel", max_length=5, help_text="Abgekürzter Name in Großbuchstaben"
    )
    penalty_points = models.IntegerField(
        "Strafpunkte", default=0, help_text="Anzahl der Strafpunkte"
    )

    logo = models.ImageField("Logo", upload_to="logos/%Y%m%d", blank=True)

    class Meta:
        verbose_name = "Mannschaft"
        verbose_name_plural = "Mannschaften"

    def __str__(self):
        return self.long_name


class Season(models.Model):
    seasonId = models.BigAutoField(primary_key=True)
    title = models.CharField("Titel", max_length=200, help_text="Titel der Saison")
    win = models.IntegerField("Sieg", default=3, help_text="Anzahl der Punkte bei Sieg")
    draw = models.IntegerField(
        "Unentschieden", default=1, help_text="Anzahl der Punkte bei Unentschieden"
    )
    defeat = models.IntegerField(
        "Niederlage", default=0, help_text="Anzahl der Punkte bei Niederlage"
    )
    count_promoted = models.PositiveIntegerField(
        "Anzahl Aufsteiger", default=3, help_text="Wieviele Aufsteiger gibt es?"
    )
    count_relegated = models.PositiveIntegerField(
        "Anzahl Absteiger", default=3, help_text="Wieviele Absteiger gibt es?"
    )
    favourite_team = models.ForeignKey(
        Team,
        default=1,
        help_text="Lieblingsmannschaft für diverse Voreinstellungen",
        on_delete=models.CASCADE,
        verbose_name="Lieblingsmannschaft",
    )

    year = models.DateField(
        "Jahr",
        help_text="Das Jahr des ersten Spieltags der Saison",
    )

    class Meta:
        verbose_name = "Saison"
        verbose_name_plural = "Saisons"

    def __str__(self):
        return self.title


class PlayingSchedule(models.Model):
    playingScheduleId = models.BigAutoField(primary_key=True)
    title = models.CharField("Titel", max_length=200, help_text="Titel des Spielplans")
    season = models.ForeignKey(
        Season,
        help_text="Spielplan gehört zu welcher Saison?",
        on_delete=models.CASCADE,
        verbose_name="Saison",
    )
    current_matchday = models.PositiveSmallIntegerField(
        "Aktueller Spieltag",
        help_text="Trage hier den aktuellen Spieltag ein, der standardmäßig angezeigt werden soll.",
        default=1,
    )

    class Meta:
        verbose_name = "Spielplan"
        verbose_name_plural = "Spielpläne"

    def __str__(self):
        return self.title


class ScheduledMatch(models.Model):
    scheduledMatchId = models.BigAutoField(primary_key=True)
    schedule = models.ForeignKey(
        PlayingSchedule,
        help_text="Spiel gehört zu welchem Spielplan?",
        on_delete=models.CASCADE,
        verbose_name="Spielplan",
    )
    home_team = models.ForeignKey(
        Team,
        related_name="homeTeam",
        help_text="Heimmannschaft",
        on_delete=models.CASCADE,
        verbose_name="Heimmannschaft",
    )
    guest_team = models.ForeignKey(
        Team,
        related_name="guestTeam",
        help_text="Gastmannschaft",
        on_delete=models.CASCADE,
        verbose_name="Gastmannschaft",
    )
    play_time = models.DateTimeField("Spielzeit", help_text="Zeitpunkt des Spiels")
    match_day = models.PositiveIntegerField(
        "Spieltag", help_text="Nummer des Spieltags", default=1
    )

    goal_count_home_team = models.IntegerField(
        "Anzahl Tore Heimmannschaft",
        help_text="Anzahl der Tore der Heimmannschaft?",
        blank=True,
        null=True,
    )
    goal_count_guest_team = models.IntegerField(
        "Anzahl Tore Auswärtsmannschaft",
        help_text="Anzahl der Tore der Auswärtsmannschaft?",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Geplantes Spiel"
        verbose_name_plural = "Geplante Spiele"

    def __str__(self):
        return "{}, Spieltag {}, {} : {}".format(
            self.schedule, self.match_day, self.home_team, self.guest_team
        )


class MatchReport(models.Model):
    matchReportId = models.BigAutoField(primary_key=True)
    scheduledMatch = models.ForeignKey(
        ScheduledMatch,
        help_text="Spielbericht gehört zu welchem Spiel?",
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        "Titel", max_length=30, help_text="Titel des Spielberichts"
    )
    text = HTMLField("Text", max_length=5000, help_text="Text des Spielberichts")
    pub_date = models.DateTimeField(
        "Zeitstempel", help_text="Zeitstempel des Spielberichts"
    )

    class Meta:
        verbose_name = "Spielbericht"
        verbose_name_plural = "Spielberichte"

    def __str__(self):
        return self.title


class Player(models.Model):
    playerId = models.BigAutoField(primary_key=True)
    name = models.CharField("Name", max_length=200, help_text="Name des Spielers")

    class Meta:
        verbose_name = "Spieler"
        verbose_name_plural = "Spieler"

    def __str__(self):
        return self.name


class PlayerMatchResult(models.Model):
    playerMatchResultId = models.BigAutoField(primary_key=True, verbose_name="Id")
    player = models.ForeignKey(
        Player,
        help_text="Ergebnis gehört zu welchem Spieler?",
        on_delete=models.CASCADE,
        verbose_name="Spieler",
    )
    scheduledMatch = models.ForeignKey(
        ScheduledMatch,
        help_text="Ergebnis gehört zu welchem Spielergebnis?",
        on_delete=models.CASCADE,
        default=5,
        verbose_name="Geplantes Spiel",
    )
    goals = models.IntegerField(
        "Tore", default=0, help_text="Anzahl der geschossenen Tore"
    )
    assists = models.IntegerField(
        "Vorlagen", default=0, help_text="Anzahl der gemachten Vorlagen"
    )
    yellow_cards = models.IntegerField(
        "Gelbe Karten", default=0, help_text="Anzahl der bekommenen gelben Karten"
    )
    yellow_red_cards = models.IntegerField(
        "Gelb-Rote Karten",
        default=0,
        help_text="Anzahl der bekommenen Gelb-Roten Karten",
    )
    red_cards = models.IntegerField(
        "Rote Karten", default=0, help_text="Anzahl der bekommenen roten Karten"
    )

    class Meta:
        verbose_name = "Spielerergebnis"
        verbose_name_plural = "Spielerergebnisse"

    def __str__(self):
        return "{}, {}".format(self.player, self.scheduledMatch)


class News(models.Model):
    newsId = models.BigAutoField(primary_key=True)
    title = models.CharField("Titel", max_length=30, help_text="Titel der Nachricht")
    text = models.TextField("Text", max_length=5000, help_text="Text der Nachricht")
    pub_date = models.DateTimeField(
        "Zeitstempel", help_text="Zeitstempel der Nachricht"
    )

    class Meta:
        verbose_name = "Neuigkeit"
        verbose_name_plural = "Neuigkeiten"

    def __str__(self):
        return self.title


class Documents(models.Model):
    documentsId = models.BigAutoField(primary_key=True)
    name = models.CharField(
        "Titel", max_length=30, help_text="Titel der Dokumentensammlung"
    )
    document = models.FileField("Dokument", upload_to="documents/%Y%m%d")
    showInFooter = models.BooleanField(
        "Zeige im Footer?",
        default=False,
        help_text="Soll dieses Dokument automatisch auf jeder Seite im Footer verlinkt dargestellt werden?",
    )

    class Meta:
        verbose_name = "Dokument"
        verbose_name_plural = "Dokumente"

    def __str__(self):
        return self.name

svh/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.core.validators import EmailValidator


class ContactForm(forms.Form):

    name = forms.CharField(
        label="Vor- und Nachname",
        max_length=120,
    )
    email = forms.CharField(
        label="E-Mail", widget=forms.EmailInput(attrs={"class": "validate"})
    )
    inquiry = forms.CharField(label="Betreff", max_length=70)
    message = forms.CharField(
        label="Nachricht",
        widget=forms.Textarea(attrs={"class": "materialize-textarea"}),
        max_length=5000,
    )

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()

        name = cl_data.get("name").strip()
        from_email = cl_data.get("email")
        subject = cl_data.get("inquiry")

        msg = f"{name} mit E-Mail {from_email} schrieb:"
        msg += f'\n"{subject}"\n\n'
        msg += cl_data.get("message")

        return subject, msg

    def send(self):

        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS],
        )

svh/templates/svh/contact.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/contact.jpg' %}" width="100vh"></div>
</div>
<div class="container">
    <div class="section">
        <form method="post">
            {% csrf_token %}
            <div class="row center">
                <h2 class="header center light-blue-text text-darken-4">Kontakt</h2>
            </div>
            <div class="row">
                <div class="input-field col s12 m6 l6">
                    {{ form.name }}
                    <label for="id_name">Vor- und Nachname</label>
                </div>
                <div class="input-field col s12 m6 l6">
                    {{ form.email }}
                    <!-- <input id="email" type="email" class="validate"> -->
                    <label for="id_email">E-Mail</label>
                    <span class="helper-text" data-error="Ungültige E-Mail-Adresse" data-success="Vielen Dank!"></span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.inquiry }}
                    <label for="id_inquiry">Betreff</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.message }}
                    <label for="id_message">Deine Nachricht</label>
                </div>
            </div>
            <div class="right-align">
                <button class="btn waves-effect waves-light orange accent-3" type="submit" name="action">
                    Senden
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

svh/templates/svh/impressum.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="section flow-text">
        <div class="row center">
            <h1 class="header center light-blue-text text-darken-4">Impressum</h1>
        </div>
        <div class="row">
            <div class="col s12">
                <h4>Angaben gemäß § 5 TMG</h4>
                <p>
                    SV Hörne 01 e.V.<br />
                    Am Siebenborn 8<br />
                    37242 Bad Sooden-Allendorf
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <h4>Kontakt</h4>
                <p>
                    E-Mail: <a href="mailto:info@svhoerne.de">info@svhoerne.de</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <h4>EU-Streitschlichtung</h4>
                <p>
                    Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: <a target="_blank" href="https://ec.europa.eu/consumers/odr/">https://ec.europa.eu/consumers/odr/</a>. Unsere E-Mail-Adresse finden Sie oben im Impressum.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <h4>Verbraucherstreitbeilegung/Universalschlichtungsstelle</h4>
                <p>
                    Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

svh/templates/svh/matchreport_detail.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/report.jpg' %}" width="100vh"></div>
</div>
<div class="container flow-text">
    <div class="section">
        <div class="row">
                <h3>{{ object.scheduledMatch }}</h3>
                <h4>{{ object.title }}</h4>
                <p>{{ object.pub_date }}</p>
                {{ object.text|safe }}
        </div>
    </div>
</div>
{% endblock %}

svh/templates/svh/matchreport_list.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/reports.jpg' %}" width="100vh"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row center">
            <h2 class="header center light-blue-text text-darken-4">Spielberichte</h2>
        </div>
        <div class="row">
            <form action="" method="GET">
                <div class="input-field col s12">
                    <select name="scheduleId" id="scheduleId">
                        <option value="" disabled selected>Wähle Spielplan</option>
                        {% for object in schedules %}
                        <option value="{{ object.playingScheduleId }}">{{ object.title }}</option>
                        {% endfor %}
                    </select>
                    <label>Spielplan</label>
                </div>
                <button class="btn waves-effect waves-light orange accent-3" type="submit">Los
                    <i class="material-icons right">send</i>
                </button>
                <input type="button" value="Zurücksetzen" class="waves-effect waves-red btn transparent" onclick="window.location.href='{% url "svh:reports" %}'">
            </form>
        </div>
        <table>
            {% for object in object_list %}
            <tr>
                <td><a href="{% url 'svh:report-detail' object.matchReportId %}">{{ object.scheduledMatch }}</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="row pagination">
        <div class="col s6">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo; erste</a>
                    <a href="?page={{ page_obj.previous_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">zurück</a>
                {% endif %}
        
                <span class="current">
                    Seite {{ page_obj.number }} von {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">weiter</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">letzte &raquo;</a>
                {% endif %}
            </span>
        </div>
        <div class="col s6 right-align">
            Anzahl pro Seite: <a href="?paginate_by=10{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">10</a>, <a href="?paginate_by=25{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">25</a>, <a href="?paginate_by=50{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">50</a>, <a href="?paginate_by=100{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">100</a>.
        </div>
    </div>
</div>
<script>
    selectElementSchedules('scheduleId', '{{ current_schedule }}');

    function selectElementSchedules(id, valueToSelect) {    
        let element = document.getElementById(id);
        element.value = valueToSelect;
    }
</script>
{% endblock %}

svh/templates/svh/matchresult_list.html
{% extends 'svh/base.html' %}

{% load mathfilters %}
{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/results.jpg' %}" width="100vh"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row center">
            <h2 class="header center light-blue-text text-darken-4">Ergebnisse</h2>
        </div>
        <div class="row">
            <form action="" method="GET">
                <div class="input-field col s12 m6">
                    <select name="scheduleId" id="scheduleId">
                        <option value="" disabled selected>Wähle Spielplan</option>
                        {% for object in schedules %}
                        <option value="{{ object.playingScheduleId }}">{{ object.title }}</option>
                        {% endfor %}
                    </select>
                    <label>Spielplan</label>
                </div>
                <div class="input-field col s12 m6">
                    <select name="untilMatchday" id="untilMatchday">
                        <option value="" disabled selected>Wähle Spieltag</option>
                        {% for object in matchdays %}
                        <option value="{{ object }}">{{ object }}</option>
                        {% endfor %}
                    </select>
                    <label>Spieltag</label>
                </div>
                <button class="btn waves-effect waves-light orange accent-3" type="submit">Los
                    <i class="material-icons right">send</i>
                </button>
                <input type="button" value="Zurücksetzen" class="waves-effect waves-red btn transparent" onclick="window.location.href='{% url "svh:results" %}'">
            </form>
        </div>

        <div class="row center">
            <h3 class="header center light-blue-text text-darken-4">Spieltag</h3>
        </div>
        <div class="row">
            <table class="striped responsive-table">
                <thead>
                    <tr>
                        <th>Spieltag</th>
                        <th>Zeit</th>
                        <th class="right-align">Heim</th>
                        <th></th>
                        <th class="right-align">Gast</th>
                        <th></th>
                        <th>Ergebnis</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in results %}
                    <tr>
                        <td>{{ object.match_day }}</td>
                        <td>{{ object.play_time }}</td>
                        <td class="right-align"><img height="30" src="/media/{{ object.home_team.logo }}"></td>
                        <td>{{ object.home_team.long_name }}</td>
                        <td class="right-align"><img height="30" src="/media/{{ object.guest_team.logo }}"></td>
                        <td>{{ object.guest_team.long_name }}</td>
                        <td>{{ object.goal_count_home_team|default_if_none:"-" }}:{{ object.goal_count_guest_team|default_if_none:"-" }}</td>
                    </tr>
                    {% empty %}
                        Keine Einträge vorhanden.
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="section">
        <div class="row center">
            <h3 class="header center light-blue-text text-darken-4">Tabelle</h3>
        </div>
        <div class="row">
            <table class="striped responsive-table">
                <thead>
                    <tr>
                        <th>Platz</th>
                        <th>Mannschaft</th>
                        <th>Spiele</th>
                        <th>S</th>
                        <th>U</th>
                        <th>N</th>
                        <th>Torverhältnis</th>
                        <th>Tordifferenz</th>
                        <th>Punkte</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    {% if object.matches > 0 %}
                    {% if forloop.counter <= count_promoted.0 %}
                    <tr class="green lighten-5">
                    {% elif forloop.counter >= object_list|length|add:1|sub:count_relegated.0 %}
                    <tr class="red lighten-5">
                    {% else %}
                    <tr>
                    {% endif %}
                        <td>{{ forloop.counter }}</td>
                        <td class="valign-wrapper"><img height="30" src="/media/{{ object.logo }}">&nbsp; {{ object.long_name }}</td>
                        <td>{{ object.matches }}</td>
                        <td>{{ object.matchesWon }}</td>
                        <td>{{ object.matchesDraw }}</td>
                        <td>{{ object.matchesLost }}</td>
                        <td>{{ object.shotGoals|default_if_none:"-" }} : {{ object.gotGoals|default_if_none:"-" }}</td>
                        <td>{{ object.goalDifference|default_if_none:"-" }}</td>
                        <td>{{ object.points }}</td>
                    </tr>
                    {% endif %}
                    {% empty %}
                    Keine Einträge vorhanden.
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    selectElementSchedules('scheduleId', '{{ current_schedule }}');

    function selectElementSchedules(id, valueToSelect) {    
        let element = document.getElementById(id);
        element.value = valueToSelect;
    }

    selectElementMatchday('untilMatchday', '{{ current_matchday }}')

    function selectElementMatchday(id, valueToSelect) {    
        let element = document.getElementById(id);
        element.value = valueToSelect;
    }
</script>
{% endblock %}

svh/templates/svh/player_list.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/players.jpg' %}" width="100vh"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row center">
            <h2 class="header center light-blue-text text-darken-4">Spieler</h2>
        </div>
        <div class="row">
            <form action="" method="GET">
                <div class="input-field col s12 m6">
                    <select name="scheduleId" id="scheduleId">
                        <option value="" disabled selected>Wähle Spielplan</option>
                        {% for object in schedules %}
                        <option class="orange-text text-accent-3" value="{{ object.playingScheduleId }}">{{ object.title }}</option>
                        {% endfor %}
                    </select>
                    <label>Spielplan</label>
                </div>
                <div class="input-field col s12 m6">
                    <select name="untilMatchday" id="untilMatchday">
                        <option value="" disabled selected>Wähle Spieltag</option>
                        {% for object in matchdays %}
                        <option value="{{ object }}">{{ object }}</option>
                        {% endfor %}
                    </select>
                    <label>Spieltag</label>
                </div>
                <button class="btn waves-effect waves-light orange accent-3" type="submit">Los
                    <i class="material-icons right">send</i>
                </button>
                <input type="button" value="Zurücksetzen" class="waves-effect waves-red btn transparent" onclick="window.location.href='{% url "svh:players" %}'">
            </form>
        </div>
        <div class="row">
            <table class="striped responsive-table">
                {% if not object_list|length == 0 %}
                <thead>
                    <tr>
                        <th>Rang</th>
                        <th>Name</th>
                        <th>Spiele</th>
                        <th>Tore</th>
                        <th>Vorlagen</th>
                        <th>Gelbe Karten</th>
                        <th>Gelb-Rote Karten</th>
                        <th>Rote Karten</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                        <td>{{ object.name|default_if_none:"-" }}</td>
                        <td>{{ object.games|default_if_none:"-" }}</td>
                        <td>{{ object.goals|default_if_none:"-" }}</td>
                        <td>{{ object.assists|default_if_none:"-" }}</td>
                        <td>{{ object.yellow_cards|default_if_none:"-" }}</td>
                        <td>{{ object.yellow_red_cards|default_if_none:"-" }}</td>
                        <td>{{ object.red_cards|default_if_none:"-" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                        Keine Einträge vorhanden.
                {% endif %}
            </table>
        </div>
        <div class="row pagination">
            <div class="col s6">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo; erste</a>
                        <a href="?page={{ page_obj.previous_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">zurück</a>
                    {% endif %}
            
                    <span class="current">
                        Seite {{ page_obj.number }} von {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">weiter</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">letzte &raquo;</a>
                    {% endif %}
                </span>
            </div>
            <div class="col s6 right-align">
                Anzahl pro Seite: <a href="?paginate_by=10{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">10</a>, <a href="?paginate_by=25{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">25</a>, <a href="?paginate_by=50{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">50</a>, <a href="?paginate_by=100{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">100</a>.
            </div>
        </div>
    </div>
</div>
<script>
    selectElementSeason('scheduleId', '{{ default_schedule }}')

    function selectElementSeason(id, valueToSelect) {    
        let element = document.getElementById(id);
        element.value = valueToSelect;
    }

    selectElementMatchday('untilMatchday', '{{ default_matchday }}')

    function selectElementMatchday(id, valueToSelect) {    
        let element = document.getElementById(id);
        element.value = valueToSelect;
    }
</script>
{% endblock %}

svh/templates/svh/success.html
{% extends 'svh/base.html' %}

{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'images/contact.jpg' %}" width="100vh"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row center">
            <h2 class="header center light-blue-text text-darken-4">Nachricht gesendet</h2>
        </div>
        <div class="row center">
            <p>Vielen Dank. Falls du eine weitere Nachricht senden möchtest, wiederhole den Vorgang.</p>
        </div>
        <div class="col l4 m12 row center">
            <a href="{% url 'svh:contact' %}" id="contact-page" class="btn-large waves-effect waves-light orange accent-3"><i class="material-icons right">contact_mail</i>Kontaktformular</a>
        </div>
    </div>
</div>

{% endblock %}